let list = [
  {
    _id: 1,
    title: "가리가리 스크래쳐 소파 와이드",
    img: "../../images/img01.png",
    price: "19,900원",
    category: "b",
    discount: "2",
  },
  {
    _id: 2,
    title: "루어캣 3D 스크래쳐 평판 2개입",
    img: "../../images/img02.png",
    price: "5,000원",
    category: "b",
    discount: "5",
  },
  {
    _id: 3,
    title: "위드캣 알뜰 평판 스크래쳐",
    img: "../../images/img03.png",
    price: "4,200원",
    category: "b",
    discount: "10",
  },
  {
    _id: 4,
    title: "네코이찌 바리바리볼 스크래쳐",
    img: "../../images/img04.png",
    price: "18,500원",
    category: "b",
    discount: "30",
  },
  {
    _id: 5,
    title: "가리가리 스크래쳐 빅서클 베이지",
    img: "../../images/img05.jpg",
    price: "22,900원",
    category: "b",
    discount: "0",
  },
  {
    _id: 6,
    title: "루어캣 스크래쳐 빅L",
    img: "../../images/img06.jpg",
    price: "30,000원",
    category: "b",
    discount: "20",
  },
  {
    _id: 7,
    title: "헬로망치 프리미엄 대형 직조 캣타워 DS",
    img: "../../images/img11.jpg",
    price: "85,000원",
    category: "s",
    discount: "0",
  },
  {
    _id: 8,
    title: "딩동펫 고양이 익사이트 우드 캣휠",
    img: "../../images/img12.jpg",
    price: "129,000원",
    category: "s",
    discount: "10",
  },
  {
    _id: 9,
    title: "가또블랑코 에펠타워 카페트 포함",
    img: "../../images/img13.jpg",
    price: "325,000원",
    category: "s",
    discount: "10",
  },
  {
    _id: 10,
    title: "멍멍아띠 캣폴 스크래쳐 고양이 캣타워",
    img: "../../images/img14.jpg",
    price: "89,000원",
    category: "s",
    discount: "10",
  },
  {
    _id: 11,
    title: "가또페로 화이트폴 브라운 B타입",
    img: "../../images/img15.jpg",
    price: "250,000원",
    category: "s",
    discount: "10",
  },
  {
    _id: 12,
    title: "헬로망치 프리미엄 대형 직조 캣타워 DS8897",
    img: "../../images/img16.jpg",
    price: "85,000원",
    category: "s",
    discount: "10",
  },
  {
    _id: 13,
    title: "펫모닝 직조 캣타워 PMC CF285-2",
    img: "../../images/img17.jpg",
    price: "155,000원",
    category: "s",
    discount: "10",
  },
];
export default list;
